# Generated by Django 4.0.4 on 2022-04-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Ingrese Nombre del Alumno')),
                ('apellido', models.CharField(max_length=45, verbose_name='Ingrese Apellido del Alumno')),
                ('edad', models.IntegerField(verbose_name='Ingreses edad del Alumno')),
                ('email', models.EmailField(max_length=254, verbose_name='Ingrese Correo del Alumno')),
                ('fecha_contratacion', models.DateField()),
            ],
        ),
    ]
