# Generated by Django 4.0.4 on 2022-05-07 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_alter_alumno_apellido_alter_alumno_edad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='profresor',
            new_name='profesor',
        ),
    ]
