# Generated by Django 4.0.4 on 2022-05-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_rename_profresor_cursos_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('comentario', models.TextField()),
            ],
        ),
    ]
